const ResumeApi = [
    {
      id: 1,
      category: "education",
      year: "Generation Australia (May 2022 - July 2022)",
      title: "Junior Web Developer Bootcamp",
      desc: "",
      rate: "",
    },
    {
      id: 2,
      category: "education",
      year: "Tehran University (2015)",
      title: "Master of Science Industrial Management",
      desc: "",
      rate: "",
    },
    {
      id: 3,
      category: "education",
      year: "Shahab-Danesh University (2011)",
      title: "Bachelor of Science in Electronics Engineering",
      desc: "",
      rate: "",
    },
    {
    id: 3,
    category: "education",
    year: "Damavand Azad University (2008)",
    title: "Associate of Science Electronics Engineering",
    desc: "",
    rate: "",
    },
    {
      id: 4,
      category: "experience",
      year: "July 2016 - March 2020",
      title: "Customer Services at Kone (Iran)",
      desc: "",
      rate: "",
    },
    {
      id: 5,
      category: "experience",
      year: "April 2014 - July 2016",
      title: "Electronics Technician at Kone (Iran)",
      desc: "",
      rate: "",
    },
    {
      id: 6,
      category: "experience",
      year: "May 2012 - April 2014",
      title: "Electronics Engineer at Asia Electronics (Iran)",
      desc: "",
      rate: "",
    },
  ]
  
  export default ResumeApi